# Generated by Django 5.2.3 on 2025-08-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_vault_earning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyandsell',
            name='duration',
            field=models.CharField(max_length=20),
        ),
    ]
