# Generated by Django 5.2.3 on 2025-08-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_alter_buyandsell_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('asset_type', models.CharField(choices=[('crypto', 'Crypto'), ('forex', 'Forex'), ('stock', 'Stock')], max_length=10)),
                ('current_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
