# Generated by Django 5.2.3 on 2025-08-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0004_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='buyandsell',
            name='entry_price',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=12),
        ),
    ]
