# Generated by Django 5.2.3 on 2025-08-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0005_alter_asset_current_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyandsell',
            name='stop_loss',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='buyandsell',
            name='take_profit',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='buyandsell',
            name='pl',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=12, verbose_name='Profit/Loss'),
        ),
    ]
