# Generated by Django 5.2.3 on 2025-08-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0006_buyandsell_stop_loss_buyandsell_take_profit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('returns', models.DecimalField(decimal_places=2, max_digits=5)),
                ('win_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('copiers', models.PositiveIntegerField()),
            ],
        ),
    ]
