# Generated by Django 5.2.3 on 2025-09-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0007_trader'),
    ]

    operations = [
        migrations.AddField(
            model_name='vault',
            name='today',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
